name: aepsych_visualizer
channels:
  - conda-forge
dependencies:
  - python==3.9.4
  - pip==22.1.1
  - jupyterlab==3.4.4
  - pip:
    - aepsych>=0.3.0
    - aepsych_client>=0.2.0
    - voila==0.3.6
    - ipywidgets==7.6.5
    - statsmodels==0.13.5
